version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: api
    volumes:
      - /home/$USER/pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'



